apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimization-api
  labels:
    app: optimization-api
  namespace: my namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimization-api
  template:
    metadata:
      labels:
        app: optimization-api
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
      - name: optimization-api
        image: digibuild.azurecr.io/digibuild/optimization-api:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        env:
         
