apiVersion: apps/v1
kind: Deployment
metadata:
  name: indoor-comfort-api
  labels:
    app: indoor-comfort-api
  namespace: my namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indoor-comfort-api
  template:
    metadata:
      labels:
        app: indoor-comfort-api
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
      - name: indoor-comfort-api
        image: digibuild.azurecr.io/digibuild/indoor-comfort-api:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        env:
          - name: KEYCLOACK_USERNAME
            value: "vcipollone"
          - name: KEYCLOACK_PASSWORD
            value: "4K@y0<u6kVD("
          - name: KEYCLOACK_URL
            value: "https://digibuild.epu.ntua.gr/auth/realms/DIGIBUILD/protocol/openid-connect/token"
          - name: URL_DATA
            value: "https://digibuild.epu.ntua.gr/data_sharing/federated_querying/execute_query/"
          - name: URL_OPENMETEO_FORECAST1
            value: "https://api.open-meteo.com/v1/forecast?latitude=60.17&longitude=24.94&hourly=temperature_2m&forecast=1&timezone=Europe/Helsinki"
          - name: URL_OPENMETEO_FORECAST7
            value: "https://api.open-meteo.com/v1/forecast?latitude=60.17&longitude=24.94&hourly=temperature_2m&forecast=7&timezone=Europe/Helsinki"
          - name: URL_WEATHER_HISTORY
            value: "https://api.open-meteo.com/v1/forecast?latitude=60.1695&longitude=24.9354&hourly=temperature_2m&past_days=7"
          - name: URL_FORECAST_FVH
            value: "https://digibuild.epu.ntua.gr/get_fvh_forecasts"
