apiVersion: apps/v1
kind: Deployment
metadata:
  name: indoor-comfort-api
  labels:
    app: indoor-comfort-api
  namespace: my namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indoor-comfort-api
  template:
    metadata:
      labels:
        app: indoor-comfort-api
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
      - name: indoor-comfort-api
        image: digibuild.azurecr.io/digibuild/indoor-comfort-api:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        env:
        
