apiVersion: v1
kind: Service
metadata:
  name: indoor-comfort-service
  namespace: my namespace
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: indoor-comfort-api
  type: ClusterIP
